### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by tlex** [sodotai/salt-root#13]
Happens when a minion doesn't have any roles set.

**Comment by tlex** [comment]
```
          ID: /usr/local/sbin/apply_firewall.sh
    Function: cmd.run
      Result: True
     Comment: Command "/usr/local/sbin/apply_firewall.sh" run
     Started: 21:04:40.137155
    Duration: 604.672 ms
     Changes:
              ----------
              pid:
                  26891
              retcode:
                  0
              stderr:
              stdout:
```
